name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: MobileApp

      - name: Create google-services.json
        working-directory: MobileApp
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      # --- Inject API Keys into local.properties ---
      - name: Create local.properties file
        working-directory: MobileApp
        run: touch local.properties

      - name: Inject Hugging Face API Token into local.properties
        working-directory: MobileApp
        run: echo "HF_API_TOKEN=${{ secrets.HF_API_TOKEN }}" >> local.properties

      - name: Inject CurrencyLayer API Key into local.properties
        working-directory: MobileApp
        run: echo "CURRENCYLAYER_API_KEY=${{ secrets.CURRENCYLAYER_API_KEY }}" >> local.properties

      - name: Generate version numbers
        id: version
        run: |
          # Use GitHub run number as version code for uniqueness
          VERSION_CODE=${{ github.run_number }}
          VERSION_NAME="1.0.$VERSION_CODE"
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "Generated versionCode: $VERSION_CODE and versionName: $VERSION_NAME"

      - name: Build release APK
        run: ./gradlew assembleDebug -PversionCode=${{ env.VERSION_CODE }} -PversionName=${{ env.VERSION_NAME }}
        working-directory: MobileApp

      - name: Upload artifact to Firebase App Distribution
        uses: nguyentrongkhanhduy/Firebase-Distribution-Github-Action@master
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: MobileApp/app/build/outputs/apk/debug/app-debug.apk
