name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: MobileApp

      - name: Create google-services.json
        working-directory: MobileApp
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: Bump versionCode and versionName
        working-directory: MobileApp/
        run: |
          versionCode=$(grep versionCode build.gradle | head -1 | awk '{print $2}')
          versionName=$(grep versionName build.gradle | head -1 | awk '{print $2}' | tr -d '"')
          newVersionCode=$((versionCode + 1))
          newVersionName="1.0.${newVersionCode}"
          sed -i "s/versionCode $versionCode/versionCode $newVersionCode/" build.gradle
          sed -i "s/versionName \"$versionName\"/versionName \"$newVersionName\"/" build.gradle
          echo "Bumped versionCode to $newVersionCode and versionName to $newVersionName"

      - name: Build release APK
        run: ./gradlew assembleDebug
        working-directory: MobileApp

      - name: Upload artifact to Firebase App Distribution
        uses: nguyentrongkhanhduy/Firebase-Distribution-Github-Action@master
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: MobileApp/app/build/outputs/apk/debug/app-debug.apk
