name: Android CI

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "Manual Debug Build"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: MobileApp

      - name: Create google-services.json
        working-directory: MobileApp
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: Build release APK
        run: ./gradlew assembleDebug
        working-directory: MobileApp

      - name: Upload artifact to Firebase App Distribution
        uses: nguyentrongkhanhduy/Firebase-Distribution-Github-Action@master
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: MobileApp/app/build/outputs/apk/debug/app-debug.apk
